
new_resolution = 840 / 1362;

files = {'024.bkp','025.bkp','027.bkp','028.bkp','029.bkp','030.bkp',...
         '031.bkp','032.bkp','033.bkp','034.bkp','035.bkp','036.bkp','037.bkp',...
         '038.bkp','039.bkp','040.bkp','041.bkp','042.bkp','043.bkp','044.bkp',...
         '045.bkp','046.bkp','047.bkp','048.bkp','049.bkp','050.bkp','051.bkp',...
         '052.bkp','053.bkp','054.bkp','055.bkp'};

         for f = files
  load('-binary', f{:}, 'images', 'mean_col_px', 'mean_dist',...
       'mean_height', 'mean_row_px', 'frame', 'tm', 'front', 'front_px',...
       'height', 'height_px', 'width', 'width_px', 'area',...
       'COL_CROP', 'ROW_CROP', 'DATA_STEP', 'IMAGE_STEP', 'START_TM', 'STOP_TM',...
       'RESOLUTION', 'THRESHOLDS', 'VALUES');
  mean_dist *= new_resolution / RESOLUTION;
  mean_height *= new_resolution / RESOLUTION;
  front *= new_resolution / RESOLUTION;
  height *= new_resolution / RESOLUTION;
  width *= new_resolution / RESOLUTION;
  area *= (new_resolution / RESOLUTION) ^ 2;
  RESOLUTION *= new_resolution / RESOLUTION;
  save('-binary', sprintf('rescaled/%s', f{:}), 'images', 'mean_col_px', 'mean_dist',...
       'mean_height', 'mean_row_px', 'frame', 'tm', 'front', 'front_px',...
       'height', 'height_px', 'width', 'width_px', 'area',...
       'COL_CROP', 'ROW_CROP', 'DATA_STEP', 'IMAGE_STEP', 'START_TM', 'STOP_TM',...
       'RESOLUTION', 'THRESHOLDS', 'VALUES');
endfor